services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_pal_backend
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./workspace
        target: /app/workspace
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: study_pal_db
    environment:
      MYSQL_DATABASE: study_pal
      MYSQL_USER: study_pal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "3306:3306"
volumes:
  db-store: